import { Inter } from 'next/font/google';
import 'bootstrap/dist/css/bootstrap.css';
import './global.css';
import WhatsAppButton from './component/WhatsAppButton';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Amp Technology',
  description: 'Generated by create next app',
};

async function getData() {
  try {
    let officeData = await fetch(`${process.env.BACKLINK}/public/officeData`, {
      headers: {
        'x-api-key': process.env.API_KEY,
        'office-id': process.env.OFFICE,
      },
      next: {
        revalidate: 600,
      },
    });
    if (!officeData.ok) {
      return console.error(`Failed to fetch office data: ${res.statusText}`);
    }

    return officeData.json();
  } catch (error) {
    console.error('Error:', error.message);
    return null;
  }
}

async function getLinks() {
  try {
    let links = await fetch(`${process.env.BACKLINK}/public/social`, {
      headers: {
        'x-api-key': process.env.API_KEY,
        'office-id': process.env.OFFICE,
      },
      cache: 'no-store',
    });

    return await links.json();
  } catch (error) {
    return null;
  }
}

export default async function RootLayout({ children }) {
  let data = await getData();
  const officeData = data?.data;
  let getSocial = await getLinks();
  const socialData = getSocial?.data[0];

  return (
    <html lang="en">
      <body className={inter.className}>
        <WhatsAppButton />
        {children}
      </body>
    </html>
  );
}
